package com.example.gymApp.dto.trainee;

import com.example.gymApp.model.Trainee;
import java.util.List;
import org.mapstruct.IterableMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;


@Mapper(componentModel = "spring")
public interface TraineeMapper {

  @Mapping(source = "firstName", target = "user.firstName")
  @Mapping(source = "lastName", target = "user.lastName")
  @Mapping(source = "dateOfBirth", target = "dateOfBirth")
  @Mapping(source = "address", target = "address")
  Trainee toTrainee(TraineeDto dto);




  @Named("toTraineeDto")
  @Mapping(target = "isActive", ignore = true)


  //did refactoring of the method name(from toTraineeDtoWith3Fields)
  default TraineeDto toTraineeDto(Trainee trainee) {
    TraineeDto dto = new TraineeDto();
    dto.setFirstName(trainee.getUser().getFirstName());
    dto.setLastName(trainee.getUser().getLastName());
    dto.setUsername(trainee.getUser().getUsername());

    return dto;
  }


  @IterableMapping(qualifiedByName = "toTraineeDto")
  List<TraineeDto> toTraineeDtoList(List<Trainee> trainees);

  /*
   The TraineeMapperImplementationMethodAutogeneratedNoUsedInMyCode method converts a single Trainee object to a
   TraineeDtoWith3fields.
The toTraineeDto3ListNew method converts a list of Trainee objects to a list of TraineeDto3fields objects,
using the mapping defined in the TraineeMapperImplementationMethodAutogeneratedNoUsedInMyCode method
     */
  @Named("toTraineeDtoWith3Fields")
  @Mapping(source = "user.firstName", target = "firstName")
  @Mapping(source = "user.lastName", target = "lastName")
  @Mapping(source = "user.username", target = "username")
  TraineeResponseDto TraineeMapperImplementationMethodAutogeneratedNoUsedInMyCode(Trainee trainee);

//  @IterableMapping(qualifiedByName = "toTraineeDtoWith3Fields")
//  List<TraineeResponseDto> toTraineeDto3ListNew(List<Trainee> trainees);
//

  //12
  @Mapping(target = "username", source = "username")
  @Mapping(target = "periodFrom", source = "periodFrom")
  @Mapping(target = "periodTo", source = "periodTo")
  @Mapping(target = "trainerName", source = "trainerName")
  @Mapping(target = "specialization", source = "specializationName")
  TraineeTrainingRequestDto toDto(
      String username,
      String periodFrom,
      String periodTo,
      String trainerName,
      String specializationName);

}






