version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: gym_db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: gym_db
    ports:
      - "5432:5432"
    networks:
      - app-network

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: gym_app
#    depends_on:
#      - postgres
#    ports:
#      - "8081:8080"
#    networks:
#      - app-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gym_db
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: user

networks:
  app-network:
    driver: bridge
