version: '3.8'

services:
  postgres_local:
    image: postgres:latest
    container_name: LOCAL_gym_db
    environment:
      POSTGRES_USER: user_local
      POSTGRES_PASSWORD: user_local
      POSTGRES_DB: gym_db_local
    ports:
      - "5432:5432"
    networks:
      - app-network

  postgres_dev:
      image: postgres:latest
      container_name: DEV_gym_db
      environment:
        POSTGRES_USER: user_dev
        POSTGRES_PASSWORD: user_dev
        POSTGRES_DB: gym_db_dev
      ports:
        - "5433:5432"
      networks:
        - app-network

  postgres_prod:
    image: postgres:latest
    container_name: PROD_gym_db
    environment:
      POSTGRES_USER: user_prod
      POSTGRES_PASSWORD: user_prod
      POSTGRES_DB: gym_db_prod
    ports:
      - "5434:5432"
    networks:
      - app-network


  postgres_stg:
    image: postgres:latest
    container_name: STG_gym_db
    environment:
      POSTGRES_USER: user_stg
      POSTGRES_PASSWORD: user_stg
      POSTGRES_DB: gym_db_stg
    ports:
      - "5435:5432"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - app-network

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin



networks:
  app-network:
    driver: bridge
